### ISSUE TITLE
Cannot run consumer from the basic blueprint

### ISSUE THREAD

**Issue by henadzit** [electronick1/stairs#1]
Hi,

While trying out the project, I run into the issue with running the consumer.

```
$python manage.py consumer:standalone core.print_smth
Standalone consumer started.
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    init_cli()
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/stairs/services/management/commands.py", line 21, in init_cli
    cli()
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/henadzit/workspace/craft/shipping-data/env/lib/python3.7/site-packages/stairs/services/management/consumer.py", line 22, in init_session
    user_app.components.consumers[consumer_name].run_worker()
AttributeError: 'Output' object has no attribute 'run_worker'
```

I haven't done any changes to the basic structure which I got from running `stairs-admin project:new project_name`.

Thanks in advance!

**Comment by electronick1** [comment]
Hi @henadzit ,

Could you please check if your consumer wrapped by`@standalone_consumer` decorator. This decorators converts simple Output to a standalone "worker" process which you can run separately from pipelines. 

Here some example:
```
@app.standalone_consumer()
def write_to_file(**data):
    f.write(json.dumps(data))
    f.write("\n")
```

**Comment by electronick1** [comment]
Hi @henadzit 

Did you manage to solve this issue? If you have any other questions please let me know will try to share more details 👍

**Comment by henadzit** [comment]
Hi @electronick1,

Sorry for not replying sooner. Yes, it solved the issue! The only thing is that I never changed the code generated by `stairs-admin project:new project_name`, so the issue was in the boilerplate. But I see that you're releasing a new version, so it might've been fixed already.
